// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoqnI_6-3M7sP85RlVWYo7wOBvPVkCNZU',
    appId: '1:446235599424:web:c9265e143bab8d7104f5a5',
    messagingSenderId: '446235599424',
    projectId: 'eating-healthy-877b4',
    authDomain: 'eating-healthy-877b4.firebaseapp.com',
    storageBucket: 'eating-healthy-877b4.firebasestorage.app',
    measurementId: 'G-H983WLHDX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCedVZgJ7ZmpR4Htq1xIbUhUWTEuEesV2A',
    appId: '1:446235599424:android:fb17b23d90605c3804f5a5',
    messagingSenderId: '446235599424',
    projectId: 'eating-healthy-877b4',
    storageBucket: 'eating-healthy-877b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp9D8Wvqd7GAD2L63zdXt7EDSi0iWUgH4',
    appId: '1:446235599424:ios:985b5a8c31eb082304f5a5',
    messagingSenderId: '446235599424',
    projectId: 'eating-healthy-877b4',
    storageBucket: 'eating-healthy-877b4.firebasestorage.app',
    iosBundleId: 'com.example.eatingHealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp9D8Wvqd7GAD2L63zdXt7EDSi0iWUgH4',
    appId: '1:446235599424:ios:985b5a8c31eb082304f5a5',
    messagingSenderId: '446235599424',
    projectId: 'eating-healthy-877b4',
    storageBucket: 'eating-healthy-877b4.firebasestorage.app',
    iosBundleId: 'com.example.eatingHealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoqnI_6-3M7sP85RlVWYo7wOBvPVkCNZU',
    appId: '1:446235599424:web:f6b2b42acf73bfef04f5a5',
    messagingSenderId: '446235599424',
    projectId: 'eating-healthy-877b4',
    authDomain: 'eating-healthy-877b4.firebaseapp.com',
    storageBucket: 'eating-healthy-877b4.firebasestorage.app',
    measurementId: 'G-HQ1B18N6ZP',
  );

}